algo:
  name: sac
  class: IRCR.algorithm.sac.SACAgent
  params:
    obs_dim: ??? # to be specified later
    action_dim: ??? # to be specified later
    action_range: ??? # to be specified later
    device: ${device}
    critic_cfg: ${double_q_critic}
    actor_cfg: ${diag_gaussian_actor}
    discount: 0.99
    init_temperature: 0.1
    alpha_lr: 1e-4
    alpha_betas: [0.9, 0.999]
    actor_lr: 3e-4
    actor_betas: [0.9, 0.999]
    actor_update_frequency: 1
    critic_lr: 3e-4
    critic_betas: [0.9, 0.999]
    critic_tau: 0.001
    critic_target_update_frequency: 1
    batch_size: 512
    
double_q_critic:
  class: IRCR.algorithm.critic.DoubleQCritic
  params:
    obs_dim: ${algo.params.obs_dim}
    action_dim: ${algo.params.action_dim}
    hidden_dim: 256
    hidden_depth: 2
    
diag_gaussian_actor:
  class: IRCR.algorithm.actor.DiagGaussianActor
  params:
    obs_dim: ${algo.params.obs_dim}
    action_dim: ${algo.params.action_dim}
    action_range: ${algo.params.action_range}
    hidden_dim: 256
    hidden_depth: 2
    log_std_bounds: [-5, 2]
